let gImgFiles =[
    'aapl.png',
    'ada.png',
    'adbe.png',
    'ai_.png',
    'amd.png',
    'amzn.png',
    'avax.png',
    'ba.png',
    'bnb.png',
    'btc.png',
    'cardano.png',
    'doge.png',
    'eth.png',
    'googl.png',
    'gs.png',
    'intc.png',
    'ko.png',
    'meta.png',
    'msft.png',
    'nflx.png',
    'nke.png',
    'nvda.png',
    'polkadot.png',
    'qqq.png',
    'roku.png',
    'shib.png',
    'smci.png',
    'sol.png',
    'sphr.png',
    'spy.png',
    'tether.png',
    'tsla.png',
    'vxx.png',
    'xrp.png',


    'sqqq.png',
    'tqqq.png',
    'x.png',
    'm.png',
    'mgm.png',
    'gd.png',
    'rtx.png',
    'jwn.png',
    'mcd.png',
    'yum.png',
    'brkb.png',
    'arkk.png',

    'zm.png',
    'etsy.png',
    'avav.png',
    'snap.png',
    'hal.png',
    'gld.png',
    'k.png',


    'blank.gif',
];